# general settings
name: 5123_MIAVSR_mix_precision_Vimeo_300K_N10
model_type: RecurrentMixPrecisionRTModel
scale: 4
num_gpu: 8  # official: 8 GPUs
manual_seed: 0
find_unused_parameters: false
use_static_graph: true
# dataset and data loader settings
datasets:
  train:
    name: Vimeo90K
    type: Vimeo90KRecurrentDataset
    dataroot_gt: ../mmagic/data/vimeo90k/GT
    dataroot_lq: ../mmagic/data/vimeo90k/BIx4
    meta_info_file: ../mmagic/data/vimeo90k/meta_info_Vimeo90K_train_GT.txt
    io_backend:
      type: disk

    num_frame: -1
    gt_size: 256
    interval_list: [1]
    random_reverse: false
    use_hflip: true
    use_rot: true
    flip_sequence: True

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 1 # 原6→1，减少CPU争用
    batch_size_per_gpu: 4  # 原3→4
    dataset_enlarge_ratio: 200
    pin_memory: true # 新增，加速数据加载
    prefetch_mode: cuda # 新增，CUDA预取

  val:
    name: Vid4
    type: VideoRecurrentTestDataset
    dataroot_gt: ../mmagic/data/Vid4/GT
    dataroot_lq: ../mmagic/data/Vid4/BIx4

    cache_data: true
    io_backend:
      type: disk

    num_frame: -1  # not needed

# network structures
network_g:
  type: MIAVSR
  mid_channels: 64
  embed_dim: 120
  depths: [6,6,6,6]
  num_heads: [6,6,6,6]
  window_size: [3, 4, 4] # 原[3,8,8]→减少显存碎片
  num_frames: 3
  img_size : 64
  patch_size : 1
  cpu_cache_length: 200 # 原100→提升缓存命中率
  is_low_res_input: True
  use_mask: True #False, may be you should pretrain this model with no mask processing module
  spynet_path: experiments/pretrained_models/flownet/spynet_sintel_final-3d2a1287.pth

# path
path:
  pretrain_network_g: ~
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2.828e-4 # 原1e-4→sqrt(8)*1e-4 线性缩放规则
    weight_decay: 0
    betas: [0.9, 0.98] #原[0.9,0.99]→更稳定收敛

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [300000]
    restart_weights: [1]
    eta_min: !!float 1e-7

  # 新增混合精度配置（网页2）
  scaler:
    type: GradScaler
    init_scale: 65536.0
    growth_interval: 2000

  total_iter: 37500 # 原300000→等效迭代次数（300000/(3 * 8)*16 * 8）
  warmup_iter: -1  # no warm up
  fix_flow: -1
  flow_lr_mul: 0.25
  parsity_target: [0.7]
  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: mean
  
  sparsity_opt:
    type: SparsityCriterion
    parsity_target: [0.7]

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: true

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
  algorithm: tree          # 强制树状通信
  gradient_accumulation_steps: 2  # 新增梯度累积
